[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
duck-chess = "0.1.1"
serde-wasm-bindgen = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
